name: Build and lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/cache@v3
        name: Restore NPM cache
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v3
        name: Restore Composer cache
        id: composer-cache
        with:
          path: '**/vendor'
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
      - run: npm ci
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
      - run: composer install
        if: ${{ steps.composer-cache.outputs.cache-hit != 'true' }}
      - run: npm run lint
      - run: npm run build
